### ISSUE TITLE
Gulp seed not working on first go.  Windows 10

### ISSUE THREAD

**Issue by jberall** [JKHeadley/appy-backend#10]
.env file =
SMTP_PASSWORD=secret
PORT=8000

typed in command gulp seed 

C:\xampp\htdocs\angular4\hapi\hapi-university\appy\node_modules\require-dir\index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (C:\xampp\htdocs\angular4\hapi\hapi-university\appy\node_modules\require-dir\index.js:93:37)
    at Object.<anonymous> (C:\xampp\htdocs\angular4\hapi\hapi-university\appy\gulpfile.js:9:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\Owner\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)

**Comment by JKHeadley** [comment]
@jberall please reference #9 for a possible fix.

**Comment by JKHeadley** [comment]
Recent releases to rest-hapi have resolved this issue.  See JKHeadley/rest-hapi#37
