### ISSUE TITLE
/login/forgot issue

### ISSUE THREAD

**Issue by jobberwalker** [JKHeadley/appy-backend#15]
Hello,
When I run api /login/forgot for the 1st time it works OK and mailed is received. 
when I post again getting the following error message:

`[16:46:45.291]  9613 ERROR    server/api/login.js:351:15 api/Forgot Password — TypeError: internals.renderTemplate(...).then is not a function
[16:46:45.291]  9613 ERROR    server/api/login.js:351:15 api/Forgot Password —     at Object.internals.sendEmail (/server/mailer.js:50:6)
[16:46:45.291]  9613 ERROR    server/api/login.js:351:15 api/Forgot Password —     at /server/api/login.js:345:25
[16:46:45.291]  9613 ERROR    server/api/login.js:351:15 api/Forgot Password —     at process._tickDomainCallback (internal/process/next_tick.js:135:7)`

**Comment by JKHeadley** [comment]
@jobberwalker this should be working now.
