### ISSUE TITLE
TypeError: require.extensions.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by djkoelz** [JKHeadley/appy-backend#9]
> gulp seed

dev/appy/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/koelzdj/dev/appy/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/koelzdj/dev/appy/gulpfile.js:9:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)

Seems to be an issue with using nodejs version 8.
Reference the following https://stackoverflow.com/questions/44298322/node-8-0-0-and-npm-4-2-0-error-express-load-require-extensions-hasownproperty-is

**Comment by djkoelz** [comment]
Downgrading to nodejs v 6.11.2 did fix the issue
